# path: JuniorLLM/src/reasoning/code_generator.py
#!/usr/bin/env python3
"""
Code Generator

Allows agents to generate, reason about, and safely propose code changes.
Part of giving agents autonomy to build and modify their own codebase.
"""

import logging
from typing import Any, Dict, Optional

logging.basicConfig(level=logging.INFO, format="[*] %(asctime)s - %(message)s")


class CodeGenerator:
    """
    Generates and reasons about code using TDA-enhanced reasoning.
    """

    def __init__(self, reasoner=None):
        self.reasoner = reasoner
        logging.info("CodeGenerator initialized")

    def generate_code(self, task_description: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        prompt = f"""Generate clean, production-grade Python code for the following task:

{task_description}

Requirements:
- Follow existing architecture patterns
- Include proper error handling
- Be efficient for edge deployment
- Add clear comments
"""

        if self.reasoner:
            reasoning = self.reasoner.reason(prompt, context=context)
        else:
            reasoning = {"reasoning": "Basic code generation (no TDA reasoner)"}

        # Placeholder for actual code generation logic
        generated_code = f"""# Auto-generated by JuniorLLM CodeGenerator
# Task: {task_description}

def generated_function():
    """ {task_description} """
    # TODO: Implement based on reasoning
    pass
"""

        return {
            "task": task_description,
            "code": generated_code,
            "reasoning": reasoning,
            "status": "generated",
        }

    def review_code(self, code: str) -> Dict[str, Any]:
        # Simple static review (can be enhanced with TDA)
        issues = []
        if "TODO" in code:
            issues.append("Contains TODOs")
        if len(code) < 50:
            issues.append("Very short implementation")

        return {
            "safe": len(issues) == 0,
            "issues": issues,
            "suggestions": ["Add more error handling", "Add type hints"],
        }
